baseURL   = "http://localhost:1313/"     # for local preview
languageCode = "en-us"
title     = "FunGen-xQTL Data Catalog"
theme     = "Blowfish"                     # or "blowfish" if you want your own

